name: raccoon
description: "A new Flutter package project."
version: 0.2.0
# homepage:
environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.7
  expandable: ^5.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
